# Generated by Django 5.2.4 on 2026-06-08 08:38

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings_goals', '0003_alter_savingsgoal_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='monthly_contribution',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
