# Generated by Django 5.2.4 on 2026-06-08 08:38

import core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0009_documentchunk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentchunk',
            new_name='document_ch_documen_53de58_idx',
            old_name='document_chunks_doc_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash to deduplicate files', max_length=64),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='text',
            field=core.encryption.EncryptedTextField(help_text='Plaintext content of this chunk (encrypted at rest)'),
        ),
        migrations.AlterField(
            model_name='scorefactordetail',
            name='metrics',
            field=core.encryption.EncryptedJSONField(help_text='Raw metrics used to calculate this factor score (encrypted)'),
        ),
        migrations.AlterField(
            model_name='spendingpattern',
            name='analysis_data',
            field=core.encryption.EncryptedJSONField(help_text='Full JSON output from AI analysis (patterns, anomalies, recommendations) (encrypted)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, default='0.00', help_text='Current wallet balance (encrypted)', max_digits=12),
        ),
    ]
