# Generated by Django 5.2.5 on 2026-06-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_rename_document_chunks_doc_idx_document_ch_documen_53de58_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
