# Generated by Django 5.2.4 on 2026-06-08 08:38

import core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=core.encryption.EncryptedDecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
