# Generated by Django 5.2.4 on 2026-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('goal', 'Goal'), ('transaction', 'Transaction'), ('funds', 'Funds'), ('system', 'System')], default='info', max_length=20),
        ),
    ]
