name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-asyncio pytest-mock coverage
        
    - name: Run Tests with Coverage
      env:
        DJANGO_SETTINGS_MODULE: core.settings
        SECRET_KEY: dummy_secret_key_for_testing_purposes
        DB_NAME: db.sqlite3
      run: |
        coverage run --source='.' manage.py test
        pytest sockets/tests.py
        coverage report
